# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f9befbd32cc09f9fec524ba9813b283ffcb4a181cfb0a36d35d25406cbed7e0ac95daa642e35a5800ceb2b262afedd35a4fe4e2821dc87a2b4c705936a70a4b

test:
  secret_key_base: d262f63127727e4aa1e5e57ffaa1e0f97f9114f4980573ef6b1ae19849770adf27d41dd409f129969818a95aa28b2ed5046d23e0a00dc4de452f1be9f59373e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
